spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lyra?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: Aup6g/t;3
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        multiTenancy: SCHEMA
        tenant_identifier_resolver: com.lyra.common.tenant.CurrentTenantIdentifierResolverImpl
        multi_tenant_connection_provider: com.lyra.common.tenant.MultiTenantConnectionProviderImpl
  redis:
    host: 127.0.0.1
    port: 6379
    password: Smtjh2020
