spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LYRA_MYSQL_IP}:3306/lyra?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        multiTenancy: SCHEMA
        tenant_identifier_resolver: com.lyra.common.tenant.CurrentTenantIdentifierResolverImpl
        multi_tenant_connection_provider: com.lyra.common.tenant.MultiTenantConnectionProviderImpl
  redis:
    host: ${LYRA_REDIS_IP}
    port: 6379
    password: Smtjh2020
